#!/usr/bin/env python3
"""ツール一覧のドキュメントを、サーバの実装と言語リソースから生成する。

手で書くと必ずずれるので、出どころを1つにする:

  * 名前・引数・既定値 … サーバの Python を **ast で読む**（import しないので
    mcp パッケージが要らず、mcp を入れていない環境でも --check が通る）
  * 説明             … locales/<lang>.json（サーバが実行時に読むのと同じもの）
  * 必要な scope     … http/mcp_server.py の TOOL_SCOPES

出力は docs/reference/tools.md（英語）と docs/reference/tools.ja.md（日本語）。
生成物はリポジトリに入れる（mkdocs serve がそのまま動くように）。tools/check.sh と
tools/deploy-docs.sh が `--check` で作り直して差分が無いことを確かめるので、
ずれたままにはならない。

  python3 tools/gen_tool_reference.py            # 生成する
  python3 tools/gen_tool_reference.py --check    # 最新かどうかだけ見る
"""
from __future__ import annotations

import ast
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ツールの並び。**実装に在るものは必ずどれかに属する**ことを検査するので、
# ツールを足したのに分類し忘れると、この生成器自体が落ちる。
GROUPS = [
    ("read", "Reading records", "レコードを読む",
     ["search_records", "get_record", "my_records",
      "list_versions", "list_revisions", "export_record"]),
    ("vocab", "Vocabularies", "語彙",
     ["list_vocabulary_types", "list_vocabulary"]),
    ("write", "Creating and updating", "作成と更新",
     ["create_record", "update_record", "publish_record",
      "new_version", "delete_draft"]),
    ("curate", "Withdrawing and restoring", "取り下げと復元",
     ["delete_record", "restore_record"]),
    ("files", "Files", "ファイル",
     ["upload_file", "add_file", "list_files", "download_file", "delete_file",
      "upload_file_from_url", "start_multipart_upload",
      "complete_multipart_upload", "abort_multipart_upload"]),
    ("communities", "Communities", "コミュニティ",
     ["search_communities", "get_community", "list_community_records",
      "create_community"]),
    ("requests", "Reviews and requests", "査読とリクエスト",
     ["list_requests", "get_request", "submit_to_community",
      "comment_on_request", "request_action"]),
    ("session", "Session", "セッション",
     ["whoami"]),
]


def _unparse(node) -> str:
    return ast.unparse(node) if node is not None else ""


def signature(fn: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    """`upload_file(recid, filename, content_base64=None, ...)` を組み立てる。"""
    args = fn.args
    positional = args.posonlyargs + args.args
    defaults = [None] * (len(positional) - len(args.defaults)) + list(args.defaults)
    parts = []
    for a, d in zip(positional, defaults):
        piece = a.arg
        if a.annotation is not None:
            piece += f": {_unparse(a.annotation)}"
        if d is not None:
            piece += f" = {_unparse(d)}"
        parts.append(piece)
    for a, d in zip(args.kwonlyargs, args.kw_defaults):
        piece = f"{a.arg}: {_unparse(a.annotation)}" if a.annotation else a.arg
        if d is not None:
            piece += f" = {_unparse(d)}"
        parts.append(piece)
    return f"{fn.name}({', '.join(parts)})"


def read_server(rel_path: str) -> tuple[dict[str, str], dict[str, str | None]]:
    """(ツール名 → シグネチャ, TOOL_SCOPES) を ast で取り出す。"""
    tree = ast.parse(open(os.path.join(ROOT, rel_path), encoding="utf-8").read())
    sigs, scopes = {}, {}
    for node in tree.body:
        if isinstance(node, ast.Assign) and getattr(node.targets[0], "id", "") == "TOOL_SCOPES":
            scopes = ast.literal_eval(node.value)
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        if any(isinstance(d, ast.Call) and isinstance(d.func, ast.Attribute)
               and d.func.attr == "tool" and getattr(d.func.value, "id", "") == "mcp"
               for d in node.decorator_list):
            sigs[node.name] = signature(node)
    return sigs, scopes


def strings(rel_dir: str, lang: str) -> dict:
    with open(os.path.join(ROOT, rel_dir, f"{lang}.json"), encoding="utf-8") as f:
        return json.load(f)


HEAD = {
    "en": """<!-- Generated by tools/gen_tool_reference.py. Do not edit by hand. -->
# Tool reference

Every tool both servers expose, with its arguments and the scope it needs. The
descriptions here are the **same strings the servers hand to the model** — they come out
of `locales/en.json`, so this page cannot drift from what a client actually sees.

- **http** — the {n_http} tools of [the HTTP server](../guides/http.md)
- **stdio** — the {n_stdio} tools of [the stdio server](../guides/stdio.md)

A tool with no scope reads public information and works unauthenticated. See
[Authorization](../concepts/authorization.md) for what each scope means.
""",
    "ja": """<!-- tools/gen_tool_reference.py が生成する。手で書き換えない。 -->
# ツール一覧

2つのサーバが公開しているすべてのツールと、その引数・必要な scope。ここに載る説明は
**サーバが実際に LLM へ渡している文字列そのもの**で、`locales/ja.json` から取っている。
クライアントが見るものとずれることがない。

- **http** — [HTTP 版](../guides/http.md)の {n_http} ツール
- **stdio** — [stdio 版](../guides/stdio.md)の {n_stdio} ツール

scope の欄が空のツールは公開情報の読取で、未認証でも呼べる。scope の意味は
[認可](../concepts/authorization.md)を見ること。
""",
}

LABELS = {
    "en": {"scope": "Scope", "signature": "Signature", "unauth": "none (unauthenticated)",
           "http_only": "HTTP server only", "stdio_only": "stdio server only",
           "both": "both servers", "avail": "Available in"},
    "ja": {"scope": "必要な scope", "signature": "呼び出し方", "unauth": "不要（未認証で可）",
           "http_only": "HTTP 版のみ", "stdio_only": "stdio 版のみ",
           "both": "両方", "avail": "提供"},
}


def render(lang: str) -> str:
    http_sigs, scopes = read_server("http/mcp_server.py")
    stdio_sigs, _ = read_server("stdio/server.py")
    http_txt = strings("http/locales", lang)["tools"]
    stdio_txt = strings("stdio/locales", lang)["tools"]
    lab = LABELS[lang]

    known = {name for _, _, _, names in GROUPS for name in names}
    missing = sorted((set(http_sigs) | set(stdio_sigs)) - known)
    if missing:
        raise SystemExit(
            f"tools not assigned to a group in GROUPS: {missing}\n"
            f"Add them to tools/gen_tool_reference.py.")

    out = [HEAD[lang].format(n_http=len(http_sigs), n_stdio=len(stdio_sigs))]
    for _, title_en, title_ja, names in GROUPS:
        out.append(f"\n## {title_en if lang == 'en' else title_ja}\n")
        for name in names:
            in_http, in_stdio = name in http_sigs, name in stdio_sigs
            if not (in_http or in_stdio):
                continue
            avail = lab["both"] if in_http and in_stdio else (
                lab["http_only"] if in_http else lab["stdio_only"])
            out.append(f"### `{name}`\n")
            rows = [f"| | |", "| --- | --- |", f"| {lab['avail']} | {avail} |"]
            if in_http:
                need = scopes.get(name)
                rows.append(f"| {lab['scope']} | "
                            f"{'`' + need + '`' if need else lab['unauth']} |")
            out.append("\n".join(rows) + "\n")
            if in_http and in_stdio and http_sigs[name] == stdio_sigs[name]:
                out.append(f"```python\n{http_sigs[name]}\n```\n")
            else:
                if in_http:
                    out.append(f"```python\n{http_sigs[name]}   # http\n```\n")
                if in_stdio:
                    out.append(f"```python\n{stdio_sigs[name]}   # stdio\n```\n")
            body = http_txt.get(name) if in_http else stdio_txt.get(name)
            if isinstance(body, list):
                body = "\n".join(body)
            out.append((body or "").rstrip() + "\n")
            if in_http and in_stdio:
                alt = stdio_txt.get(name)
                if isinstance(alt, list):
                    alt = "\n".join(alt)
                if alt and alt.strip() != (body or "").strip():
                    note = ("The stdio version differs:" if lang == "en"
                            else "stdio 版はふるまいが違う:")
                    out.append(f"\n!!! note \"{note}\"\n\n    "
                               + alt.rstrip().replace("\n", "\n    ") + "\n")
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    check = "--check" in sys.argv
    stale = []
    for lang, name in (("en", "tools.md"), ("ja", "tools.ja.md")):
        path = os.path.join(ROOT, "docs", "reference", name)
        new = render(lang)
        old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if check:
            if new != old:
                stale.append(os.path.relpath(path, ROOT))
            continue
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(new)
        print(("unchanged " if new == old else "wrote      ")
              + os.path.relpath(path, ROOT))
    if stale:
        print("out of date: " + ", ".join(stale))
        print("run: python3 tools/gen_tool_reference.py")
        return 1
    if check:
        print("tool reference is up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
